management.endpoints.web.exposure.include: '*'
spring:
  rabbitmq:
    username: admin
    password: admin
    host: 192.168.1.105
    port: 5672
    virtual-host: /
server:
  port: 0
  
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:24246/eureka}