management.endpoints.web.exposure.include: '*'

server:
  port: 0
  
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:24246/eureka}
    
events:
  user-service:
    exchanges:
      - exchange:
          name: user-service-exchange
          type: header
        queues: 
          - queue:
              name: user-service-events
              bindining: user.event.#