management.endpoints.web.exposure.include: '*'
server.context-path: /api/listing
server:
  port: 0
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
  client:    
    register-with-eureka: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:24246/eureka}
spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/listingdb
    username: user
    password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc.lob.non_contextual_creation: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    