spring:
  rabbitmq:
    user: admin
    password: admin
    host: 127.0.0.1
    port: 15672
    vhost: /
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG