management:
  endpoints:
    web:
      exposure:
        include: '*'
server.context-path: /api/user
spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc.lob.non_contextual_creation: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    