spring:
  rabbitmq:
    user: guest
    password: guest
    host: localhost
    port: 5672
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG